apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: otus-four
automountServiceAccountToken: true

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: business-service-sa
  namespace: otus-four
automountServiceAccountToken: true


