apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: auth-virtual-service
  namespace: otus-four
spec:
  hosts:
    - arch.homework 
  gateways:
    - otus-four-gateway 
  http:
    - name: "auth-routes"
      match:
        - uri:
            prefix: "/register"
        - uri:
            prefix: "/login"
        - uri:
            prefix: "/public-key"
      route:
        - destination:
            host: auth-service.otus-four.svc.cluster.local
            subset: v1
    - name: "business-routes"
      # match:
      #   - uri:
      #       exact: "/"
      route:
        - destination:
            host: business-service.otus-four.svc.cluster.local
            subset: v1
